title: Leonardo Bertolani
description: Data Scientist, Software Engineer, and Tech Enthusiast
baseurl: ""
url: "https://leonardobertolani.github.io"
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
